[package]
name = "yatwm"
version = "0.2.0"
edition = "2024"

[dependencies]
fern = "0.7.1"
indexmap = "2.13.0"
log = "0.4.29"
maplit = "1.0.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
x11rb = "0.13.2"
xkb = "0.3.0"
